language: node_js
node_js:
  - 10.16.3
before_script:
  - yarn install
before_deploy:
  - yarn build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET_NAME
    skip_cleanup: true
    local_dir: build